/*
  Warnings:

  - The values [CARDIOLOGY,DERMATOLOGY,ENDOCRINOLOGY,GASTROENTEROLOGY,HEMATOLOGY,FAMILY_MEDICINE,DERMATOVENEREOLOGY,ENDOCRINOLOGY_AND_METABOLISM,GASTROENTEROHEPATOLOGY,GENERAL_SURGERY,GERIATRICS,HEMATOLOGY_AND_MEDICAL_ONCOLOGY,INFECTIOUS_DISEASES,INTERNAL_MEDICINE_AND_RHEUMATOLOGY] on the enum `Specializations` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "Specializations_new" AS ENUM ('SURGERY', 'GYNECOLOGY', 'NEUROLOGY', 'OPHTHALMOLOGY', 'OTOLARYNGOLOGY', 'PEDIATRICS', 'PSYCHIATRY', 'UROLOGY', 'ONCOLOGY', 'PULMONOLOGY', 'RHEUMATOLOGY', 'ANESTHESIOLOGY', 'ORTHOPEDICS', 'PATHOLOGY', 'RADIOLOGY', 'DENTISTRY', 'DIETETICS', 'BIOCHEMISTRY');
ALTER TABLE "doctors" ALTER COLUMN "speciality" DROP DEFAULT;
ALTER TABLE "doctors" ALTER COLUMN "speciality" TYPE "Specializations_new" USING ("speciality"::text::"Specializations_new");
ALTER TYPE "Specializations" RENAME TO "Specializations_old";
ALTER TYPE "Specializations_new" RENAME TO "Specializations";
DROP TYPE "Specializations_old";
ALTER TABLE "doctors" ALTER COLUMN "speciality" SET DEFAULT 'SURGERY';
COMMIT;
