import { PrismaClient, Prisma } from "@prisma/client";
import { hashPassword } from "../src/lib/hashPassword";
const prisma = new PrismaClient();

async function seed() {
  const examinationDictionarySeedData: Prisma.ExaminationDictionaryCreateInput[] =
    [
      {
        type: "Physical",
        description: "Physical Examination",
      },
      {
        type: "Laboratory",
        description: "Laboratory Examination",
      },
      {
        type: "Radiology",
        description: "Radiology Examination",
      },
      {
        type: "Cardiology",
        description: "Cardiology Examination",
      },
      {
        type: "Dermatology",
        description: "Dermatology Examination",
      },
      {
        type: "Ophthalmology",
        description: "Ophthalmology Examination",
      },
      {
        type: "Gastroenterology",
        description: "Gastroenterology Examination",
      },
      {
        type: "Neurology",
        description: "Neurology Examination",
      },
      {
        type: "Endocrinology",
        description: "Endocrinology Examination",
      },
      {
        type: "Orthopedics",
        description: "Orthopedics Examination",
      },
      // Add more seed data as needed
    ];
  const userData: Prisma.UserCreateInput[] = [
    {
      firstName: "Viktor",
      lastName: "Didyk",
      nationalId: "90071204975",
      id: "1",
      email: "viktor@gmail.com",
      emailVerified: "2023-04-07T21:05:53.424Z",
      password: await hashPassword("password123"),
      patient: { create: { insuranceId: "123456789" } },
    },
    {
      firstName: "John",
      lastName: "Kennedy",
      nationalId: "78050101019",
      id: "2",
      email: "kennedy@gmail.com",
      password: await hashPassword("password123"),

      patient: { create: { insuranceId: "123458" } },
    },
    {
      firstName: "Richard",
      lastName: "Dixon",
      nationalId: "67102002594",
      id: "3",
      email: "dixon@gmail.com",
      emailVerified: "2023-04-07T21:05:53.424Z",
      password: await hashPassword("password123"),

      patient: { create: { insuranceId: "987456" } },
    },
    {
      firstName: "Andrii",
      lastName: "Bobchuk",
      sex: "yes",
      id: "4",
      nationalId: "75092305414",
      email: "andrii@gmail.com",
      emailVerified: "2023-04-07T21:05:53.424Z",
      password: await hashPassword("password123"),
      role: "RECEPTIONIST",
      receptionist: { create: {} },
    },
    {
      firstName: "Mike",
      lastName: "Smaluch",
      sex: "sometimes",
      id: "5",
      nationalId: "00071503585",
      email: "michal@gmail.com",
      emailVerified: "2023-04-07T21:05:53.424Z",
      password: await hashPassword("password123"),
      role: "DOCTOR",
      doctor: { create: {speciality: "NEUROLOGY"} },
    },
    {
      firstName: "Asser",
      lastName: "Elfeki",
      sex: "polsl",
      id: "6",
      nationalId: "65123106530",
      email: "asser@gmail.com",
      emailVerified: "2023-04-07T21:05:53.424Z",
      password: await hashPassword("password123"),
      role: "LAB_ASSISTANT",
      labAssistant: { create: {} },
    },
    {
      firstName: "Youssef",
      lastName: "Al Bali",
      sex: "always",
      id: "7",
      nationalId: "07110303373",
      email: "ydm@gmail.com",
      emailVerified: "2023-04-07T21:05:53.424Z",
      password: await hashPassword("password123"),
      role: "DOCTOR",
      doctor: { create: {speciality: "GYNECOLOGY"} },
    },
    {
      firstName: "Abraham",
      lastName: "Lincoln",
      nationalId: "88032504053",
      id: "8",
      email: "lincoln@gmail.com",
      emailVerified: "2023-04-07T21:05:53.424Z",
      password: await hashPassword("password123"),

      patient: { create: { insuranceId: "12345678987" } },
    },
    {
      firstName: "MohammedVI",
      lastName: "Alawi",
      nationalId: "93052605606",
      id: "9",
      email: "alawi@gmail.com",
      emailVerified: "2023-04-07T21:05:53.424Z",
      password: await hashPassword("password123"),

      patient: { create: { insuranceId: "1234" } },
    },
    {
      firstName: "Tutankhamun",
      lastName: "Pharanon",
      nationalId: "28061602591",
      id: "10",
      email: "pharaon@gmail.com",
      emailVerified: "2023-04-07T21:05:53.424Z",
      password: await hashPassword("password123"),

      patient: { create: { insuranceId: "12345" } },
    },
    {
      firstName: "John",
      lastName: "Travolta",
      nationalId: "50020708028",
      id: "11",
      email: "travolta@gmail.com",
      emailVerified: "2023-04-07T21:05:53.424Z",
      password: await hashPassword("password123"),

      patient: { create: { insuranceId: "12345678" } },
    },
    {
      firstName: "Yoda",
      lastName: "Magister",
      nationalId: "66093000262",
      id: "12",
      email: "yoda@gmail.com",
      emailVerified: "2023-04-07T21:05:53.424Z",
      password: await hashPassword("password123"),

      patient: { create: { insuranceId: "9876" } },
    },
    {
      firstName: "Anakin",
      lastName: "Skywalker",
      nationalId: "22082702542",
      id: "13",
      email: "anakin@gmail.com",
      emailVerified: "2023-04-07T21:05:53.424Z",
      password: await hashPassword("password123"),

      patient: { create: { insuranceId: "1337228" } },
    },
    {
      firstName: "JarJar",
      lastName: "Binks",
      nationalId: "67062905708",
      id: "14",
      email: "binks@gmail.com",
      emailVerified: "2023-04-07T21:05:53.424Z",
      password: await hashPassword("password123"),

      patient: { create: { insuranceId: "2281337" } },
    },
    {
      firstName: "Obi-Wan",
      lastName: "Kenoby",
      sex: "04689234",
      id: "15",
      nationalId: "11050609712",
      email: "kenoby@gmail.com",
      emailVerified: "2023-04-07T21:05:53.424Z",
      password: await hashPassword("password123"),
      role: "DOCTOR",
      doctor: { create: { speciality : "SURGERY" } },
    },
    {
      firstName: "R2",
      lastName: "D2",
      sex: "4372957",
      id: "16",
      nationalId: "26082202460",
      email: "r2@gmail.com",
      emailVerified: "2023-04-07T21:05:53.424Z",
      password: await hashPassword("password123"),
      role: "DOCTOR",
      doctor: { create: {speciality: "BIOCHEMISTRY"} },
    },
    {
      firstName: "Jesus",
      lastName: "Christ",
      sex: "god",
      id: "17",
      nationalId: "51031005436",
      email: "jesus@gmail.com",
      emailVerified: "2023-04-07T21:05:53.424Z",
      password: await hashPassword("password123"),
      role: "DOCTOR",
      doctor: { create: {speciality: "DENTISTRY"} },
    },
    {
      firstName: "Juda",
      lastName: "Iscariot",
      sex: "18",
      id: "18",
      nationalId: "33042105811",
      email: "juda@gmail.com",
      emailVerified: "2023-04-07T21:05:53.424Z",
      password: await hashPassword("password123"),
      role: "DOCTOR",
      doctor: { create: {speciality: "ANESTHESIOLOGY"} },
    },
    {
      firstName: "Vitaliy",
      lastName: "Klitchko",
      sex: "god",
      id: "19",
      nationalId: "47070600509",
      email: "klitchko@gmail.com",
      emailVerified: "2023-04-07T21:05:53.424Z",
      password: await hashPassword("password123"),
      role: "DOCTOR",
      doctor: { create: {speciality: "ANESTHESIOLOGY"} },
    },
    {
      firstName: "Habib",
      lastName: "Nurmagomedov",
      sex: "mma",
      id: "20",
      nationalId: "25080105218",
      email: "habib@gmail.com",
      emailVerified: "2023-04-07T21:05:53.424Z",
      password: await hashPassword("password123"),
      role: "DOCTOR",
      doctor: { create: {speciality: "ANESTHESIOLOGY"} },
    },
    {
      firstName: "Damian",
      lastName: "Warzecha",
      sex: "man",
      id: "21",
      nationalId: "03090803597",
      email: "damian@gmail.com",
      emailVerified: "2023-04-07T21:05:53.424Z",
      password: await hashPassword("password123"),
      role: "DOCTOR",
      doctor: { create: {speciality: "PSYCHIATRY"} },
    },
    {
      firstName: "Urszula",
      lastName: "Stanczyk",
      sex: "mma",
      id: "22",
      nationalId: "83092908353",
      email: "urszula@gmail.com",
      emailVerified: "2023-04-07T21:05:53.424Z",
      password: await hashPassword("password123"),
      role: "DOCTOR",
      doctor: { create: {speciality: "PSYCHIATRY"} },
    },
    {
      firstName: "Pikachu",
      lastName: "Pokemon",
      sex: "pokemon",
      id: "23",
      nationalId: "77051209900",
      email: "pikachu@gmail.com",
      emailVerified: "2023-04-07T21:05:53.424Z",
      password: await hashPassword("password123"),
      role: "DOCTOR",
      doctor: { create: {speciality: "RADIOLOGY"} },
    },
    {
      firstName: "Bulbazaur",
      lastName: "Pokemon",
      sex: "pokemon",
      id: "24",
      nationalId: "36042403224",
      email: "bulbazaur@gmail.com",
      emailVerified: "2023-04-07T21:05:53.424Z",
      password: await hashPassword("password123"),
      role: "DOCTOR",
      doctor: { create: {speciality: "PEDIATRICS"} },
    },
    {
      firstName: "Raichu",
      lastName: "Pokemon",
      sex: "pokemon",
      id: "25",
      nationalId: "82071308001",
      email: "raichu@gmail.com",
      emailVerified: "2023-04-07T21:05:53.424Z",
      password: await hashPassword("password123"),
      role: "DOCTOR",
      doctor: { create: {speciality: "RADIOLOGY"} },
    },
    {
      firstName: "Magikarp",
      lastName: "Pokemon",
      sex: "pokemon",
      id: "26",
      nationalId: "79062608536",
      email: "magikarp@gmail.com",
      emailVerified: "2023-04-07T21:05:53.424Z",
      password: await hashPassword("password123"),
      role: "DOCTOR",
      doctor: { create: {speciality: "DIETETICS"} },
    },
    {
      firstName: "Phillip",
      lastName: "Fry",
      sex: "pokemon",
      id: "27",
      nationalId: "02052805466",
      email: "fry@gmail.com",
      emailVerified: "2023-04-07T21:05:53.424Z",
      password: await hashPassword("password123"),
      role: "DOCTOR",
      doctor: { create: {speciality: "DIETETICS"} },
    },
    {
      firstName: "Leela",
      lastName: "Turanga",
      nationalId: "95041702000",
      id: "28",
      email: "leela@gmail.com",
      emailVerified: "2023-04-07T21:05:53.424Z",
      password: await hashPassword("password123"),

      patient: { create: { insuranceId: "12334234" } },
    },
    {
      firstName: "Hikaru",
      lastName: "Nakamura",
      nationalId: "04032005011",
      id: "29",
      email: "hikaru@gmail.com",
      emailVerified: "2023-04-07T21:05:53.424Z",
      password: await hashPassword("password123"),

      patient: { create: { insuranceId: "1223334234" } },
    },
    {
      firstName: "Magnus",
      lastName: "Carlsen",
      nationalId: "70112700684",
      id: "30",
      email: "magnus@gmail.com",
      emailVerified: "2023-04-07T21:05:53.424Z",
      password: await hashPassword("password123"),

      patient: { create: { insuranceId: "9223334234" } },
    },
    {
      firstName: "Alexander",
      lastName: "Grischuk",
      nationalId: "59042209492",
      id: "31",
      email: "alexander@gmail.com",
      emailVerified: "2023-04-07T21:05:53.424Z",
      password: await hashPassword("password123"),

      patient: { create: { insuranceId: "93334234" } },
    },
    {
      firstName: "Kirito",
      lastName: "SAO",
      nationalId: "82022109774",
      id: "32",
      email: "kirito@gmail.com",
      emailVerified: "2023-04-07T21:05:53.424Z",
      password: await hashPassword("password123"),

      patient: { create: { insuranceId: "93214234" } },
    },
    {
      firstName: "Galileo",
      lastName: "Galiley",
      sex: "science",
      id: "33",
      nationalId: "68092509230",
      email: "galileo@gmail.com",
      emailVerified: "2023-04-07T21:05:53.424Z",
      password: await hashPassword("password123"),
      role: "DOCTOR",
      doctor: { create: {speciality: "OPHTHALMOLOGY"} },
    },
    {
      firstName: "Eevee",
      lastName: "Pokemon",
      sex: "pokemon",
      id: "34",
      nationalId: "13090502396",
      email: "eeve@gmail.com",
      emailVerified: "2023-04-07T21:05:53.424Z",
      password: await hashPassword("password123"),
      role: "DOCTOR",
      doctor: { create: {speciality: "PEDIATRICS"} },
    },
    {
      firstName: "Psyduck",
      lastName: "Pokemon",
      sex: "pokemon",
      id: "35",
      nationalId: "87052909754",
      email: "psyduck@gmail.com",
      emailVerified: "2023-04-07T21:05:53.424Z",
      password: await hashPassword("password123"),
      role: "DOCTOR",
      doctor: { create: {speciality: "UROLOGY"} },
    },
    {
      firstName: "Stalker",
      lastName: "Sanya",
      sex: "Man",
      id: "36",
      nationalId: "02052501232",
      email: "stalker@gmail.com",
      emailVerified: "2023-04-07T21:05:53.424Z",
      password: await hashPassword("password123"),
      role: "DOCTOR",
      doctor: { create: {speciality: "ONCOLOGY"} },
    },
    {
      firstName: "Gregory",
      lastName: "House",
      sex: "Man",
      id: "37",
      nationalId: "95110105132",
      email: "house@gmail.com",
      emailVerified: "2023-04-07T21:05:53.424Z",
      password: await hashPassword("password123"),
      role: "DOCTOR",
      doctor: { create: {speciality: "PULMONOLOGY"} },
    },
    {
      firstName: "Ricardo",
      lastName: "Milos",
      sex: "Man",
      id: "38",
      nationalId: "23062704099",
      email: "ricardo@gmail.com",
      emailVerified: "2023-04-07T21:05:53.424Z",
      password: await hashPassword("password123"),
      role: "DOCTOR",
      doctor: { create: {speciality: "RHEUMATOLOGY"} },
    },
    {
      firstName: "Sadam",
      lastName: "Housein",
      sex: "Man",
      id: "39",
      nationalId: "10110508440",
      email: "sadam@gmail.com",
      emailVerified: "2023-04-07T21:05:53.424Z",
      password: await hashPassword("password123"),
      role: "DOCTOR",
      doctor: { create: {speciality: "ORTHOPEDICS"} },
    },
    {
      firstName: "Devops",
      lastName: "Engineer",
      sex: "Man",
      id: "40",
      nationalId: "56091200818",
      email: "devops@gmail.com",
      emailVerified: "2023-04-07T21:05:53.424Z",
      password: await hashPassword("password123"),
      role: "DOCTOR",
      doctor: { create: {speciality: "PATHOLOGY"} },
    },
  ];
  const visitData: Prisma.VisitCreateInput[] = [
    {
      description: "First visit",
      diagnosis: "Common cold",
      visitId :"1",
      date: "2023-03-29T16:30:00.000Z",
      doctor: { connect: { employeeId: "7" } },
      patient: { connect: { patientId: "1" } },
      receptionist: { connect: { employeeId: "4" } },
    },
    {
      description: "second visit",
      visitId :"2",
      diagnosis: "Common cold",
      date: "2024-01-29T16:30:00.000Z",
      doctor: { connect: { employeeId: "5" } },
      patient: { connect: { patientId: "1" } },
      receptionist: { connect: { employeeId: "4" } },
    },
    {
      description: "Follow-up visit",
      visitId :"3",
      diagnosis: "Sprained ankle",
      date: "2023-03-29T16:30:00.000Z",
      doctor: { connect: { employeeId: "7" } },
      patient: { connect: { patientId: "2" } },
      receptionist: { connect: { employeeId: "4" } },
    },
    {
      description: "Yearly check-up",
      diagnosis: "Healthy",
      visitId :"4",
      date: "2023-03-29T16:30:00.000Z",
      doctor: { connect: { employeeId: "7" } },
      patient: { connect: { patientId: "3" } },
      receptionist: { connect: { employeeId: "4" } },
    },
    {
      description: "Impotent",
      diagnosis: "Impotent",
      visitId :"5",
      date: "2023-03-29T16:30:00.000Z",
      doctor: { connect: { employeeId: "15" } },
      patient: { connect: { patientId: "8" } },
      receptionist: { connect: { employeeId: "4" } },
    },
    {
      description: "The patient died",
      diagnosis: "Typhus",
      visitId :"6",
      date: "2023-03-29T16:30:00.000Z",
      doctor: { connect: { employeeId: "17" } },
      patient: { connect: { patientId: "14" } },
      receptionist: { connect: { employeeId: "4" } },
    },
    {
      description: "Choped legs",
      diagnosis: "NNW",
      visitId :"7",
      date: "2023-03-29T16:30:00.000Z",
      doctor: { connect: { employeeId: "15" } },
      patient: { connect: { patientId: "13" } },
      receptionist: { connect: { employeeId: "4" } },
    },
    {
      description: "Choped arms",
      diagnosis: "NNW",
      visitId :"8",
      date: "2023-03-29T16:30:00.000Z",
      doctor: { connect: { employeeId: "16" } },
      patient: { connect: { patientId: "13" } },
      receptionist: { connect: { employeeId: "4" } },
    },
    {
      description: "Flue",
      diagnosis: "Flue",
      visitId :"9",
      date: "2023-03-29T16:30:00.000Z",
      doctor: { connect: { employeeId: "15" } },
      patient: { connect: { patientId: "1" } },
      receptionist: { connect: { employeeId: "4" } },
    },
    {
      description: "Unconscious",
      diagnosis: "Overdose",
      visitId :"10",
      date: "2023-03-29T16:30:00.000Z",
      doctor: { connect: { employeeId: "18" } },
      patient: { connect: { patientId: "1" } },
      receptionist: { connect: { employeeId: "4" } },
    },
    {
      description: "Unconscious",
      diagnosis: "Overdose",
      visitId :"11",
      date: "2023-03-29T16:30:00.000Z",
      doctor: { connect: { employeeId: "18" } },
      patient: { connect: { patientId: "1" } },
      receptionist: { connect: { employeeId: "4" } },
    },
    {
      description: "A bit of blood",
      diagnosis: "Shot",
      visitId :"12",
      date: "2023-03-29T16:30:00.000Z",
      doctor: { connect: { employeeId: "18" } },
      patient: { connect: { patientId: "2" } },
      receptionist: { connect: { employeeId: "4" } },
    },
    {
      description: "A bit of more blood",
      diagnosis: "Shot for sure",
      visitId :"13",
      date: "2023-03-29T16:30:00.000Z",
      doctor: { connect: { employeeId: "17" } },
      patient: { connect: { patientId: "2" } },
      receptionist: { connect: { employeeId: "4" } },
    },
    {
      description: "Afraid of people",
      diagnosis: "Amnesia",
      visitId :"14",
      date: "2023-03-29T16:30:00.000Z",
      doctor: { connect: { employeeId: "19" } },
      patient: { connect: { patientId: "3" } },
      receptionist: { connect: { employeeId: "4" } },
    },
    {
      description: "Afraid of publicity",
      diagnosis: "USA president",
      visitId :"15",
      date: "2023-03-29T16:30:00.000Z",
      doctor: { connect: { employeeId: "20" } },
      patient: { connect: { patientId: "3" } },
      receptionist: { connect: { employeeId: "4" } },
    },
    {
      description: "No slaves",
      diagnosis: "Free country",
      visitId :"16",
      date: "2023-03-29T16:30:00.000Z",
      doctor: { connect: { employeeId: "19" } },
      patient: { connect: { patientId: "8" } },
      receptionist: { connect: { employeeId: "4" } },
    },
    {
      description: "nice hat",
      diagnosis: "Shot",
      visitId :"17",
      date: "2023-03-29T16:30:00.000Z",
      doctor: { connect: { employeeId: "20" } },
      patient: { connect: { patientId: "8" } },
      receptionist: { connect: { employeeId: "4" } },
    },
    {
      description: "God",
      diagnosis: "Healthy",
      visitId :"18",
      date: "2023-03-29T16:30:00.000Z",
      doctor: { connect: { employeeId: "21" } },
      patient: { connect: { patientId: "9" } },
      receptionist: { connect: { employeeId: "4" } },
    },
    {
      description: "ded",
      diagnosis: "Typhus",
      visitId :"19",
      date: "2023-03-29T16:30:00.000Z",
      doctor: { connect: { employeeId: "20" } },
      patient: { connect: { patientId: "9" } },
      receptionist: { connect: { employeeId: "4" } },
    },
    {
      description: "not ded",
      diagnosis: "OK",
      visitId :"20",
      date: "2023-03-29T16:30:00.000Z",
      doctor: { connect: { employeeId: "21" } },
      patient: { connect: { patientId: "10" } },
      receptionist: { connect: { employeeId: "4" } },
    },
    {
      description: "ded",
      diagnosis: "Old guy",
      visitId :"21",
      date: "2023-03-29T16:30:00.000Z",
      doctor: { connect: { employeeId: "22" } },
      patient: { connect: { patientId: "10" } },
      receptionist: { connect: { employeeId: "4" } },
    },
    {
      description: "didnt pass dct",
      diagnosis: "Stupid",
      visitId :"22",
      date: "2023-03-29T16:30:00.000Z",
      doctor: { connect: { employeeId: "22" } },
      patient: { connect: { patientId: "11" } },
      receptionist: { connect: { employeeId: "4" } },
    },
    {
      description: "didnt pass aods",
      diagnosis: "Stupid",
      visitId :"23",
      date: "2023-03-29T16:30:00.000Z",
      doctor: { connect: { employeeId: "22" } },
      patient: { connect: { patientId: "12" } },
      receptionist: { connect: { employeeId: "4" } },
    },
    {
      description: "Do or do not there is no try",
      diagnosis: "Smart",
      visitId :"24",
      date: "2023-03-29T16:30:00.000Z",
      doctor: { connect: { employeeId: "23" } },
      patient: { connect: { patientId: "12" } },
      receptionist: { connect: { employeeId: "4" } },
    },
    {
      description: "Hates sand",
      diagnosis: "Nice hair",
      visitId :"25",
      date: "2023-03-29T16:30:00.000Z",
      doctor: { connect: { employeeId: "23" } },
      patient: { connect: { patientId: "13" } },
      receptionist: { connect: { employeeId: "4" } },
    },
    {
      description: "One eye",
      diagnosis: "cyclop",
      visitId :"26",
      date: "2023-03-29T16:30:00.000Z",
      doctor: { connect: { employeeId: "24" } },
      patient: { connect: { patientId: "28" } },
      receptionist: { connect: { employeeId: "4" } },
    },
    {
      description: "Looks up all the time and likes juicers",
      diagnosis: "Chess prodigy",
      visitId :"27",
      date: "2023-03-29T16:30:00.000Z",
      doctor: { connect: { employeeId: "24" } },
      patient: { connect: { patientId: "29" } },
      receptionist: { connect: { employeeId: "4" } },
    },
    {
      description: "Nice and smart woman",
      diagnosis: "Waifu",
      visitId :"28",
      date: "2023-03-29T16:30:00.000Z",
      doctor: { connect: { employeeId: "25" } },
      patient: { connect: { patientId: "28" } },
      receptionist: { connect: { employeeId: "4" } },
    },
    {
      description: "Captures Captures Captures Captures",
      diagnosis: "Japanese but not really",
      visitId :"29",
      date: "2023-03-29T16:30:00.000Z",
      doctor: { connect: { employeeId: "25" } },
      patient: { connect: { patientId: "29" } },
      receptionist: { connect: { employeeId: "4" } },
    },
    {
      description: "He is not a prodigy",
      diagnosis: "prodigy",
      visitId :"30",
      date: "2023-03-29T16:30:00.000Z",
      doctor: { connect: { employeeId: "26" } },
      patient: { connect: { patientId: "30" } },
      receptionist: { connect: { employeeId: "4" } },
    },
    {
      description: "He will crush me as a baby",
      diagnosis: "Tall and can play chess a bit",
      visitId :"31",
      date: "2023-03-29T16:30:00.000Z",
      doctor: { connect: { employeeId: "26" } },
      patient: { connect: { patientId: "31" } },
      receptionist: { connect: { employeeId: "4" } },
    },
    {
      description: "WCC",
      diagnosis: "Drinks a lot",
      visitId :"32",
      date: "2023-03-29T16:30:00.000Z",
      doctor: { connect: { employeeId: "27" } },
      patient: { connect: { patientId: "30" } },
      receptionist: { connect: { employeeId: "4" } },
    },
    {
      description: "Usually goes smoking after move 40",
      diagnosis: "Time trouble",
      visitId :"33",
      date: "2023-03-29T16:30:00.000Z",
      doctor: { connect: { employeeId: "27" } },
      patient: { connect: { patientId: "31" } },
      receptionist: { connect: { employeeId: "4" } },
    },
    {
      description: "Hard to make jokes",
      diagnosis: "No sense of humour",
      visitId :"34",
      date: "2023-03-29T16:30:00.000Z",
      doctor: { connect: { employeeId: "27" } },
      patient: { connect: { patientId: "32" } },
      receptionist: { connect: { employeeId: "4" } },
    },
  ]

  const labExaminationData: Prisma.LaboratoryExaminationCreateInput[] = [
    {
      examinationDictionary: {
        create: { type: "Covid test", description: "Covid test" },
      },
      doctorNote: "Patient is anemic",
      status: "ORDERED",
      testId : "1",
      supervisorNote: "",
      dateOfApprovalXorRejection: "2023-03-29T16:30:00.000Z",
      dateOfExecutionXorCancelling: "2023-03-29T16:30:00.000Z",
      visit: { connect: { visitId: "1" } },
      labAssistant: { connect: { employeeId: "6" } },
    },
    {
      examinationDictionary: {
        create: { type: "Heart test", description: "Heart issues" },
      },
      testId : "2",
      doctorNote: "Patient have some problems with his heart",
      status: "ORDERED",
      supervisorNote: "",
      dateOfApprovalXorRejection: "2023-03-29T16:30:00.000Z",
      dateOfExecutionXorCancelling: "2023-03-29T16:30:00.000Z",
      visit: { connect: { visitId: "2" } },
      labAssistant: { connect: { employeeId: "6" } },
    },
    {
      examinationDictionary: {
        create: { type: "Blood test", description: "Full blood panel" },
      },
      testId : "3",
      doctorNote: "Patient needs a full blood workup",
      status: "ORDERED",
      supervisorNote: "",
      dateOfApprovalXorRejection: "2023-05-12T08:00:00.000Z",
      dateOfExecutionXorCancelling: "2023-03-29T16:30:00.000Z",
      visit: { connect: { visitId: "5" } },
      labAssistant: { connect: { employeeId: "6" } },
    },

    {
      examinationDictionary: {
        create: { type: "MRI", description: "Head scan" },
      },
      testId : "4",
      doctorNote: "Patient has persistent headaches",
      status: "ORDERED",
      supervisorNote: "",
      dateOfApprovalXorRejection: "2023-05-12T08:00:00.000Z",
      dateOfExecutionXorCancelling: "2023-03-29T16:30:00.000Z",
      visit: { connect: { visitId: "8" } },
      labAssistant: { connect: { employeeId: "6" } },
    },

    {
      examinationDictionary: {
        create: { type: "Urinalysis", description: "Routine urine test" },
      },
      testId : "5",
      doctorNote: "Patient needs a routine urine test",
      status: "ORDERED",
      supervisorNote: "",
      dateOfApprovalXorRejection: "2023-05-12T08:00:00.000Z",
      dateOfExecutionXorCancelling: "2023-03-29T16:30:00.000Z",
      visit: { connect: { visitId: "12" } },
      labAssistant: { connect: { employeeId: "6" } },
    },
    {
      examinationDictionary: {
        create: { type: "Stool test", description: "Gastrointestinal issues" },
      },
      testId : "6",
      doctorNote: "Patient has been experiencing gastrointestinal issues",
      status: "ORDERED",
      supervisorNote: "",
      dateOfApprovalXorRejection: "2023-05-12T12:00:00.000Z",
      dateOfExecutionXorCancelling: "2023-03-29T16:30:00.000Z",
      visit: { connect: { visitId: "16" } },
      labAssistant: { connect: { employeeId: "6" } },
    },

    {
      examinationDictionary: {
        create: { type: "Thyroid function test", description: "Thyroid function evaluation" },
      },
      testId : "7",
      doctorNote: "Patient has a family history of thyroid issues",
      status: "ORDERED",
      supervisorNote: "",
      dateOfApprovalXorRejection: "2023-05-12T12:00:00.000Z",
      dateOfExecutionXorCancelling: "2023-03-29T16:30:00.000Z",
      visit: { connect: { visitId: "20" } },
      labAssistant: { connect: { employeeId: "6" } },
    },

    {
      examinationDictionary: {
        create: { type: "Pap smear", description: "Cervical cancer screening" },
      },
      testId : "8",
      doctorNote: "Patient needs a routine pap smear",
      status: "ORDERED",
      supervisorNote: "",
      dateOfApprovalXorRejection: "2023-05-12T12:00:00.000Z",
      dateOfExecutionXorCancelling: "2023-03-29T16:30:00.000Z",
      visit: { connect: { visitId: "24" } },
      labAssistant: { connect: { employeeId: "6" } },
    },
    {
      examinationDictionary: {
        create: { type: "Vitamin D test", description: "Vitamin D deficiency evaluation" },
      },
      testId : "9",
      doctorNote: "Patient has a history of vitamin D deficiency",
      status: "ORDERED",
      supervisorNote: "",
      dateOfApprovalXorRejection: "2023-05-12T15:00:00.000Z",
      dateOfExecutionXorCancelling: "2023-03-29T16:30:00.000Z",
      visit: { connect: { visitId: "21" } },
      labAssistant: { connect: { employeeId: "6" } },
    }
    ,
    {
      examinationDictionary: {
        create: { type: "Chest X-ray", description: "Lung function evaluation" },
      },
      testId : "10",
      doctorNote: "Patient has been experiencing chest pain and difficulty breathing",
      status: "ORDERED",
      supervisorNote: "",
      dateOfApprovalXorRejection: "2023-05-12T15:00:00.000Z",
      dateOfExecutionXorCancelling: "2023-03-29T16:30:00.000Z",
      visit: { connect: { visitId: "22" } },
      labAssistant: { connect: { employeeId: "6" } },
    }
    ,
    {
      examinationDictionary: {
        create: { type: "Allergy test", description: "Allergy evaluation" },
      },
      testId : "11",
      doctorNote: "Patient has been experiencing allergy symptoms",
      status: "ORDERED",
      supervisorNote: "",
      dateOfApprovalXorRejection: "2023-05-12T15:00:00.000Z",
      dateOfExecutionXorCancelling: "2023-03-29T16:30:00.000Z",
      visit: { connect: { visitId: "26" } },
      labAssistant: { connect: { employeeId: "6" } },
    },

    {
      examinationDictionary: {
        create: { type: "Urine pregnancy test", description: "Pregnancy confirmation" },
      },
      testId : "12",
      doctorNote: "Patient suspects she may be pregnant",
      status: "ORDERED",
      supervisorNote: "",
      dateOfApprovalXorRejection: "2023-05-12T15:00:00.000Z",
      dateOfExecutionXorCancelling: "2023-03-29T16:30:00.000Z",
      visit: { connect: { visitId: "27" } },
      labAssistant: { connect: { employeeId: "6" } },
    },
    {
      examinationDictionary: {
        create: { type: "Glucose test", description: "Blood sugar evaluation" },
      },
      testId : "13",
      doctorNote: "Patient has a history of diabetes",
      status: "ORDERED",
      supervisorNote: "",
      dateOfApprovalXorRejection: "2023-05-12T15:00:00.000Z",
      dateOfExecutionXorCancelling: "2023-03-29T16:30:00.000Z",
      visit: { connect: { visitId: "10" } },
      labAssistant: { connect: { employeeId: "6" } }, 
    },
    {
      examinationDictionary: {
        create: { type: "Glucose test2", description: "Blood sugar evaluation" },
      },
      testId : "14",
      doctorNote: "Patient has a history of diabetes",
      status: "ORDERED",
      supervisorNote: "",
      dateOfApprovalXorRejection: "2023-05-12T15:00:00.000Z",
      dateOfExecutionXorCancelling: "2023-03-29T16:30:00.000Z",
      visit: { connect: { visitId: "10" } },
      labAssistant: { connect: { employeeId: "6" } },
    },
    {
      examinationDictionary: {
        create: { type: "Blood test", description: "Complete blood count" },
      },
      testId : "15",
      doctorNote: "Patient reports feeling fatigued",
      status: "ORDERED",
      supervisorNote: "",
      dateOfApprovalXorRejection: "2023-05-12T16:30:00.000Z",
      dateOfExecutionXorCancelling: "2023-03-29T16:30:00.000Z",
      visit: { connect: { visitId: "5" } },
      labAssistant: { connect: { employeeId: "6" } },
    },

    {
      examinationDictionary: {
        create: { type: "Stool test", description: "Gastrointestinal evaluation" },
      },
      testId : "16",
      doctorNote: "Patient has been experiencing abdominal pain and irregular bowel movements",
      status: "ORDERED",
      supervisorNote: "",
      dateOfApprovalXorRejection: "2023-05-12T16:30:00.000Z",
      dateOfExecutionXorCancelling: "2023-03-29T16:30:00.000Z",
      visit: { connect: { visitId: "8" } },
      labAssistant: { connect: { employeeId: "6" } },
    },

    {
      examinationDictionary: {
        create: { type: "Thyroid test", description: "Thyroid function evaluation" },
      },
      testId : "17",
      doctorNote: "Patient has a family history of thyroid disease",
      status: "ORDERED",
      supervisorNote: "",
      dateOfApprovalXorRejection: "2023-05-12T16:30:00.000Z",
      dateOfExecutionXorCancelling: "2023-03-29T16:30:00.000Z",
      visit: { connect: { visitId: "12" } },
      labAssistant: { connect: { employeeId: "6" } },
    },

    {
      examinationDictionary: {
        create: { type: "HIV test", description: "HIV detection" },
      },
      testId : "18",
      doctorNote: "Patient is due for a routine HIV test",
      status: "ORDERED",
      supervisorNote: "",
      dateOfApprovalXorRejection: "2023-05-12T16:30:00.000Z",
      dateOfExecutionXorCancelling: "2023-03-29T16:30:00.000Z",
      visit: { connect: { visitId: "16" } },
      labAssistant: { connect: { employeeId: "6" } },
    },

    {
      examinationDictionary: {
        create: { type: "Urinalysis", description: "Kidney function evaluation" },
      },
      testId : "19",
      doctorNote: "Patient has a history of kidney disease",
      status: "ORDERED",
      supervisorNote: "",
      dateOfApprovalXorRejection: "2023-05-12T16:30:00.000Z",
      dateOfExecutionXorCancelling: "2023-03-29T16:30:00.000Z",
      visit: { connect: { visitId: "20" } },
      labAssistant: { connect: { employeeId: "6" } },
    },


  ];
  const physicalExaminationData: Prisma.PhysicalExaminationCreateInput[] = [
    {
      examinationDictionary: {
        create: { type: "Covid test", description: "Covid test" },
      },
      physicalExamId : "1",
      visit: { connect: { visitId: "1" } },
    },

    {
      examinationDictionary: {
        create: { type: "Heart", description: "Heart problems" },
      },
      physicalExamId : "2",
      visit: { connect: { visitId: "2" } },
    },
    {
      examinationDictionary: {
        create: { type: "Leg", description: "Leg problems" },
      },
      physicalExamId : "3",
      visit: { connect: { visitId: "3" } },
    },
    {
      examinationDictionary: {
        create: { type: "Toe", description: "Toe problems" },
      },
      physicalExamId : "4",
      visit: { connect: { visitId: "2" } },
    },
    {
      examinationDictionary: {
        create: { type: "Brain", description: "Brain problems" },
      },
      physicalExamId : "5",
      visit: { connect: { visitId: "4" } },
    },
    {
      examinationDictionary: {
        create: { type: "Ear", description: "ear problems" },
      },
      physicalExamId : "6",
      visit: { connect: { visitId: "6" } },
    },
    {
      examinationDictionary: {
        create: { type: "Tongue", description: "Tongue problems" },
      },
      physicalExamId : "7",
      visit: { connect: { visitId: "7" } },
    },
    {
      examinationDictionary: {
        create: { type: "Middle leg", description: "Leg problems" },
      },
      physicalExamId : "8",
      visit: { connect: { visitId: "8" } },
    },
    {
      examinationDictionary: {
        create: { type: "Imagination", description: "Imagination problems" },
      },
      physicalExamId : "9",
      visit: { connect: { visitId: "9" } },
    },
    {
      examinationDictionary: {
        create: { type: "Something", description: "no idea problems" },
      },
      physicalExamId : "10",
      visit: { connect: { visitId: "10" } },
    },
    {
      examinationDictionary: {
        create: { type: "Tractor", description: "Tractor problems" },
      },
      physicalExamId : "11",
      visit: { connect: { visitId: "11" } },
    },
    {
      examinationDictionary: {
        create: { type: "Ear", description: "Def problems" },
      },
      physicalExamId : "12",
      visit: { connect: { visitId: "12" } },
    },
    {
      examinationDictionary: {
        create: { type: "Holera", description: "Witchery problems" },
      },
      physicalExamId : "13",
      visit: { connect: { visitId: "12" } },
    },
    {
      examinationDictionary: {
        create: { type: "My hero", description: "Academy" },
      },
      physicalExamId : "14",
      visit: { connect: { visitId: "12" } },
    },
  ];
  for (const user of userData) {
    const u = await prisma.user.create({ data: user });
    console.log(`Created user with id: ${u.id}`);
  }

  for (const visit of visitData) {
    const v = await prisma.visit.create({ data: visit });
    console.log(`Created visit with id: ${v.visitId}`);
  }
  for (const labExamination of labExaminationData) {
    const l = await prisma.laboratoryExamination.create({
      data: labExamination,
    });
    console.log(`Created labExamination with id: ${l.testId}`);
  }
  for (const physicalExamination of physicalExaminationData) {
    const p = await prisma.physicalExamination.create({
      data: physicalExamination,
    });
    console.log(`Created physicalExamination with id: ${p.physicalExamId}`);
  }
  for (const examinationDictionary of examinationDictionarySeedData) {
    const e = await prisma.examinationDictionary.create({
      data: examinationDictionary,
    });
    console.log(`Created examinationDictionary with id: ${e.code}`);
  }
}

async function main() {
  console.log(`Start seeding ...`);
  await seed();
  console.log(`Seeding finished.`);
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
  });
