-- CreateEnum
CREATE TYPE "Specializations" AS ENUM ('SURGERY', 'CARDIOLOGY', 'DERMATOLOGY', 'ENDOCRINOLOGY', 'GASTROENTEROLOGY', 'GYNECOLOGY', 'HEMATOLOGY', 'NEUROLOGY', 'OPHTHALMOLOGY', 'OTOLARYNGOLOGY', 'PEDIATRICS', 'PSYCHIATRY', 'UROLOGY', 'ONCOLOGY', 'PULMONOLOGY', 'RHEUMATOLOGY', 'ANESTHESIOLOGY', 'FAMILY_MEDICINE', 'ORTHOPEDICS', 'PATHOLOGY', 'RADIOLOGY', 'BIOCHEMISTRY', 'DENTISTRY', 'DERMATOVENEREOLOGY', 'DIETETICS', 'ENDOCRINOLOGY_AND_METABOLISM', 'GASTROENTEROHEPATOLOGY', 'GENERAL_SURGERY', 'GERIATRICS', 'HEMATOLOGY_AND_MEDICAL_ONCOLOGY', 'INFECTIOUS_DISEASES', 'INTERNAL_MEDICINE_AND_RHEUMATOLOGY');

-- AlterTable
ALTER TABLE "doctors" ADD COLUMN     "Speciality" "Specializations" NOT NULL DEFAULT 'SURGERY';
